jdk: oraclejdk8
language: java
sudo: false

cache:
  directories:
  - $HOME/.m2


before_install: mvn install -N -Dgpg.skip=true
install: mvn clean install -DskipTests -T 3C -Dgpg.skip=true

script: mvn clean test -Dgpg.skip=true